//! Reading xkbcommon's V1 keymap dump: the live keymap as complete text and
//! a statement tokenizer over it.
//!
//! The input is machine-generated by xkbcommon's serializer, and the reader
//! relies on that shape: sections open at the start of a line
//! (`xkb_keycodes "…" {`), every statement ends in `;`, strings are
//! double-quoted, and there are no comments. Braces, brackets, parentheses
//! and strings are still matched properly, so nested `{ … }` and bracketed
//! lists never confuse a statement boundary. libxkbcommon 1.6 (CI) and 1.13
//! spell some things differently (`symbols[Group1]` vs `symbols[1]`, keysym
//! names vs hex); every reader here accepts both.

use std::ops::Range;

/// The keymap as V1 text with nothing left out.
///
/// libxkbcommon 1.12+ drops the key types and compat entries no key uses
/// from `xkb_keymap_get_as_string` (unless asked with
/// `XKB_KEYMAP_SERIALIZE_KEEP_UNUSED` through `xkb_keymap_get_as_string2`).
/// Xorg keeps its whole type table and compat map, and a later mapping
/// change may need an interpret no key uses yet (after `keycode 66 =
/// Control_L`, a key still in Lock matches `Any+Exactly(Lock)`). The
/// `xkbcommon` crate predates the call, so it is looked up at run time;
/// older libraries have no such trimming and their plain dump is complete.
pub(crate) fn keymap_text(keymap: &xkbcommon::xkb::Keymap) -> String {
    type GetAsString2 = unsafe extern "C" fn(
        *mut xkbcommon::xkb::ffi::xkb_keymap,
        std::ffi::c_int,
        std::ffi::c_int,
    ) -> *mut std::ffi::c_char;
    /// `XKB_KEYMAP_FORMAT_TEXT_V1`, `XKB_KEYMAP_SERIALIZE_KEEP_UNUSED`.
    const FORMAT_TEXT_V1: std::ffi::c_int = 1;
    const SERIALIZE_KEEP_UNUSED: std::ffi::c_int = 1 << 1;
    static GET_AS_STRING2: std::sync::OnceLock<Option<GetAsString2>> = std::sync::OnceLock::new();
    let get = GET_AS_STRING2.get_or_init(|| {
        // SAFETY: dlsym with RTLD_DEFAULT and a NUL-terminated name only
        // looks the symbol up; a non-null result is libxkbcommon's
        // `xkb_keymap_get_as_string2`, whose C signature `GetAsString2` is.
        let sym = unsafe { libc::dlsym(libc::RTLD_DEFAULT, c"xkb_keymap_get_as_string2".as_ptr()) };
        (!sym.is_null()).then(|| {
            // SAFETY: see above; same size, it's a function pointer.
            unsafe { std::mem::transmute::<*mut std::ffi::c_void, GetAsString2>(sym) }
        })
    });
    if let Some(get) = get {
        // SAFETY: the keymap pointer is live for the borrow; the result is a
        // malloc'd NUL-terminated string (or NULL) that we own and free.
        unsafe {
            let raw = get(keymap.get_raw_ptr(), FORMAT_TEXT_V1, SERIALIZE_KEEP_UNUSED);
            if !raw.is_null() {
                let text = std::ffi::CStr::from_ptr(raw).to_string_lossy().into_owned();
                libc::free(raw.cast());
                return text;
            }
        }
    }
    keymap.get_as_string(xkbcommon::xkb::KEYMAP_FORMAT_TEXT_V1)
}

/// The dump didn't have the shape xkbcommon writes.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum DumpError {
    /// The text has no such section.
    MissingSection(&'static str),
    /// A brace, bracket or string in the named part doesn't close.
    Malformed(&'static str),
}

impl std::fmt::Display for DumpError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingSection(s) => write!(f, "keymap text has no {s} section"),
            Self::Malformed(s) => write!(f, "unbalanced brace, bracket or string in {s}"),
        }
    }
}

impl std::error::Error for DumpError {}

/// The top-level statements of the section `keyword` opens, each trimmed
/// and with its `;`; `None` when the text has no such section.
pub(crate) fn section_statements<'a>(
    text: &'a str,
    keyword: &'static str,
) -> Result<Option<Vec<&'a str>>, DumpError> {
    let Some(body) = section(text, keyword)? else {
        return Ok(None);
    };
    Ok(Some(
        statements(text, body, keyword)?
            .into_iter()
            .map(|r| &text[r])
            .collect(),
    ))
}

/// The byte range between the braces of the section `keyword` opens.
fn section(text: &str, keyword: &'static str) -> Result<Option<Range<usize>>, DumpError> {
    let Some(start) = text.match_indices(keyword).map(|(i, _)| i).find(|&i| {
        (i == 0 || text.as_bytes()[i - 1] == b'\n')
            && text[i + keyword.len()..]
                .chars()
                .next()
                .is_some_and(|c| c.is_whitespace() || c == '"' || c == '{')
    }) else {
        return Ok(None);
    };
    let open = start
        + text[start..]
            .find('{')
            .ok_or(DumpError::Malformed(keyword))?;
    let close = matching_close(text.as_bytes(), open).ok_or(DumpError::Malformed(keyword))?;
    Ok(Some(open + 1..close))
}

/// The top-level statements of a section body, each from its first non-blank
/// byte to just past its `;`.
fn statements(
    text: &str,
    body: Range<usize>,
    section: &'static str,
) -> Result<Vec<Range<usize>>, DumpError> {
    let bytes = text.as_bytes();
    let mut out = Vec::new();
    let mut i = body.start;
    loop {
        while i < body.end && bytes[i].is_ascii_whitespace() {
            i += 1;
        }
        if i >= body.end {
            return Ok(out);
        }
        let start = i;
        let mut depth = 0usize;
        loop {
            if i >= body.end {
                return Err(DumpError::Malformed(section));
            }
            match bytes[i] {
                b'"' => {
                    i = skip_string(bytes, i).ok_or(DumpError::Malformed(section))?;
                    continue;
                }
                b'{' | b'[' | b'(' => depth += 1,
                b'}' | b']' | b')' => {
                    depth = depth.checked_sub(1).ok_or(DumpError::Malformed(section))?;
                }
                b';' if depth == 0 => break,
                _ => {}
            }
            i += 1;
        }
        i += 1;
        out.push(start..i);
    }
}

/// The statements inside the braces of `stmt` (`interpret … { a; b; };`).
pub(crate) fn body_statements(stmt: &str) -> Result<Vec<&str>, DumpError> {
    let Some(open) = stmt.find('{') else {
        return Ok(Vec::new());
    };
    let close = matching_close(stmt.as_bytes(), open).ok_or(DumpError::Malformed("statement"))?;
    Ok(split_top_level(&stmt[open + 1..close], b';'))
}

/// The comma-separated fields inside the braces of a `key <N> { … };`.
pub(crate) fn body_fields(stmt: &str) -> Result<Vec<&str>, DumpError> {
    let Some(open) = stmt.find('{') else {
        return Ok(Vec::new());
    };
    let close = matching_close(stmt.as_bytes(), open).ok_or(DumpError::Malformed("statement"))?;
    Ok(split_top_level(&stmt[open + 1..close], b','))
}

/// Index of the `}` closing the `{` at `open`.
fn matching_close(bytes: &[u8], open: usize) -> Option<usize> {
    let mut depth = 0usize;
    let mut i = open;
    while i < bytes.len() {
        match bytes[i] {
            b'"' => {
                i = skip_string(bytes, i)?;
                continue;
            }
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
        i += 1;
    }
    None
}

/// Index just past the string literal that opens at `open`.
fn skip_string(bytes: &[u8], open: usize) -> Option<usize> {
    let mut i = open + 1;
    while i < bytes.len() {
        match bytes[i] {
            b'\\' => i += 2,
            b'"' => return Some(i + 1),
            _ => i += 1,
        }
    }
    None
}

/// Split at top-level `sep`, trimmed, empty pieces dropped.
pub(crate) fn split_top_level(s: &str, sep: u8) -> Vec<&str> {
    let bytes = s.as_bytes();
    let mut out = Vec::new();
    let mut depth = 0usize;
    let mut start = 0;
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'"' => {
                i = skip_string(bytes, i).unwrap_or(bytes.len());
                continue;
            }
            b'{' | b'[' | b'(' => depth += 1,
            b'}' | b']' | b')' => depth = depth.saturating_sub(1),
            c if c == sep && depth == 0 => {
                out.push(s[start..i].trim());
                start = i + 1;
            }
            _ => {}
        }
        i += 1;
    }
    out.push(s[start..].trim());
    out.retain(|p| !p.is_empty());
    out
}

/// The contents of the first double-quoted string in `s`, unescaped as
/// xkbcommon writes strings (`\\`, `\"`, `\n`, octal).
pub(crate) fn quoted(s: &str) -> Option<String> {
    let start = s.find('"')? + 1;
    let bytes = s.as_bytes();
    let mut out = Vec::new();
    let mut i = start;
    while i < bytes.len() {
        match bytes[i] {
            b'"' => return Some(String::from_utf8_lossy(&out).into_owned()),
            b'\\' if i + 1 < bytes.len() => {
                i += 1;
                match bytes[i] {
                    b'n' => out.push(b'\n'),
                    b't' => out.push(b'\t'),
                    b'r' => out.push(b'\r'),
                    b'b' => out.push(8),
                    b'f' => out.push(12),
                    b'v' => out.push(11),
                    b'e' => out.push(27),
                    b'0'..=b'7' => {
                        let mut v = 0u32;
                        let mut n = 0;
                        while n < 3 && i < bytes.len() && (b'0'..=b'7').contains(&bytes[i]) {
                            v = v * 8 + u32::from(bytes[i] - b'0');
                            i += 1;
                            n += 1;
                        }
                        out.push(u8::try_from(v & 0xff).unwrap_or(0));
                        continue;
                    }
                    c => out.push(c),
                }
            }
            c => out.push(c),
        }
        i += 1;
    }
    None
}

/// `1`, `Group1`, `group 1`, `Level2` → the number.
pub(crate) fn index_number(s: &str) -> Option<usize> {
    let s = s.trim();
    let digits = s
        .trim_start_matches(|c: char| c.is_ascii_alphabetic())
        .trim();
    digits.parse().ok()
}

/// `key[Group2]= v` → `("key", Some("Group2"), Some("v"))`, `key` →
/// `("key", None, None)`: split at the first `=`, the index raw.
pub(crate) fn field(s: &str) -> (&str, Option<&str>, Option<&str>) {
    let (lhs, value) = match s.split_once('=') {
        Some((l, v)) => (l.trim(), Some(v.trim())),
        None => (s.trim(), None),
    };
    match lhs.split_once('[') {
        Some((k, idx)) => (k.trim(), Some(idx.trim_end_matches(']').trim()), value),
        None => (lhs, None, value),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn field_splits_both_spellings() {
        assert_eq!(
            field("symbols[Group2]= [ a, b ]"),
            ("symbols", Some("Group2"), Some("[ a, b ]"))
        );
        assert_eq!(index_number("Group2"), Some(2));
        assert_eq!(index_number("2"), Some(2));
        assert_eq!(field("groupsClamp"), ("groupsClamp", None, None));
        assert_eq!(
            field("map[Shift]= Level2"),
            ("map", Some("Shift"), Some("Level2"))
        );
        assert_eq!(index_number("Level2"), Some(2));
    }

    #[test]
    fn quoted_unescapes() {
        assert_eq!(
            quoted(r#"name[1]="a\"b\\c\101";"#).as_deref(),
            Some("a\"b\\cA")
        );
    }
}
