//! Edits over xkbcommon's V1 keymap dump (#171).
//!
//! xkbcommon keymaps are immutable and expose no structured access to types,
//! actions or behaviors, so a runtime mapping change (ChangeKeyboardMapping,
//! SetModifierMapping) takes the live keymap's
//! `get_as_string(KEYMAP_FORMAT_TEXT_V1)`, edits it here, and hands the result
//! to [`crate::kms::core::KmsCore::install_keymap_text`]. The compiler then
//! re-derives actions and the vmodmap from the compat interprets, which is what
//! Xorg's `XkbUpdateDescActions` does after `XkbUpdateKeyTypesFromCore`.
//!
//! The input is machine-generated by xkbcommon's serializer, and the parser
//! relies on that shape: sections open at the start of a line
//! (`xkb_keycodes "…" {`, `xkb_symbols "…" {`), every statement ends in `;`,
//! strings are double-quoted, and there are no comments. Braces, brackets and
//! strings are still matched properly, so nested `{ … }` (multi-keysym levels)
//! and bracketed lists never confuse a statement boundary.

use std::{collections::HashSet, fmt, ops::Range};

use crate::kms::xkb::REAL_MOD_NAMES;

/// `XkbNumKbdGroups`: a key has at most four groups.
const MAX_GROUPS: usize = 4;

/// `XKB_KEYSYM_MAX`: the largest keysym libxkbcommon accepts.
const KEYSYM_MAX: u32 = 0x1fff_ffff;

/// One group of a key as a runtime mapping change describes it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct KeyGroupSpec {
    /// Explicit key type; `None` lets the compiler pick one from the keysyms.
    pub type_name: Option<String>,
    /// One keysym per shift level, level 1 first; `0` is `NoSymbol`.
    pub keysyms: Vec<u32>,
}

/// Why an edit of the keymap text was refused. The text is left unchanged.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum XkbEditError {
    /// The text has no `xkb_keycodes` / `xkb_symbols` section.
    MissingSection(&'static str),
    /// A brace, bracket or string in the named section doesn't close.
    Malformed(&'static str),
    /// The key name is neither a keycode name nor an alias.
    UnknownKey(String),
    /// More groups than XKB allows.
    TooManyGroups(usize),
    /// A type name that can't be written as an XKB string.
    BadTypeName(String),
    /// Keycodes below 8 don't exist in X.
    InvalidKeycode(u8),
    /// Every candidate name for the keycode is already taken.
    NoFreeKeyName(u8),
    /// The keycode is in more than one modifier; keymap text keeps one per
    /// key (xkbcommon and xkbcomp both drop all but the last).
    MultipleModifiers(u8),
}

impl fmt::Display for XkbEditError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingSection(s) => write!(f, "keymap text has no {s} section"),
            Self::Malformed(s) => write!(f, "unbalanced brace, bracket or string in {s}"),
            Self::UnknownKey(k) => write!(f, "no key named <{k}>"),
            Self::TooManyGroups(n) => write!(f, "{n} groups (XKB allows {MAX_GROUPS})"),
            Self::BadTypeName(t) => write!(f, "type name {t:?} can't be written"),
            Self::InvalidKeycode(kc) => write!(f, "keycode {kc} is below the X minimum of 8"),
            Self::NoFreeKeyName(kc) => write!(f, "no free key name for keycode {kc}"),
            Self::MultipleModifiers(kc) => {
                write!(
                    f,
                    "keycode {kc} is in several modifiers; XKB text allows one"
                )
            }
        }
    }
}

impl std::error::Error for XkbEditError {}

/// The name `keycode` has in `xkb_keycodes` (not an alias), if any.
pub(crate) fn keycode_name(text: &str, keycode: u8) -> Result<Option<String>, XkbEditError> {
    let body = section(text, "xkb_keycodes")?;
    Ok(statements(text, body, "xkb_keycodes")?
        .into_iter()
        .filter_map(|r| keycode_def(&text[r]))
        .find(|&(_, kc)| kc == u32::from(keycode))
        .map(|(name, _)| name.to_owned()))
}

/// Make sure `keycode` has a name in `xkb_keycodes`, adding `<Innn> = nnn;`
/// when it has none (ChangeKeyboardMapping and SetModifierMapping may target
/// a keycode the keymap never named). Returns the text and the name.
pub(crate) fn ensure_keycode_name(
    text: &str,
    keycode: u8,
) -> Result<(String, String), XkbEditError> {
    if keycode < 8 {
        return Err(XkbEditError::InvalidKeycode(keycode));
    }
    let body = section(text, "xkb_keycodes")?;
    let stmts = statements(text, body.clone(), "xkb_keycodes")?;
    let mut taken = HashSet::new();
    let mut last_def: Option<Range<usize>> = None;
    let mut minimum: Option<(Range<usize>, u32)> = None;
    let mut maximum: Option<(Range<usize>, u32)> = None;
    for r in &stmts {
        let stmt = &text[r.clone()];
        if let Some((name, kc)) = keycode_def(stmt) {
            if kc == u32::from(keycode) {
                return Ok((text.to_owned(), name.to_owned()));
            }
            taken.insert(name.to_owned());
            last_def = Some(r.clone());
        } else if let Some(alias) = alias_def(stmt) {
            taken.insert(alias.to_owned());
        } else if let Some(v) = assignment(stmt, "minimum") {
            minimum = Some((r.clone(), v));
        } else if let Some(v) = assignment(stmt, "maximum") {
            maximum = Some((r.clone(), v));
        }
    }
    // Four characters at most: key names are 4 bytes on the X wire.
    let name = ['I', 'J', 'K', 'L']
        .iter()
        .map(|p| format!("{p}{keycode:03}"))
        .find(|n| !taken.contains(n))
        .ok_or(XkbEditError::NoFreeKeyName(keycode))?;

    let kc = u32::from(keycode);
    let mut edits: Vec<(Range<usize>, String)> = Vec::new();
    if let Some((r, v)) = minimum
        && kc < v
    {
        edits.push((r, format!("minimum = {kc};")));
    }
    if let Some((r, v)) = maximum
        && kc > v
    {
        edits.push((r, format!("maximum = {kc};")));
    }
    let line = format!("\t<{name}> = {kc};\n");
    let at = last_def.map_or(body.start, |r| line_extent(text, r).end);
    if at == body.start && !text[..at].ends_with('\n') {
        edits.push((at..at, format!("\n{line}")));
    } else {
        edits.push((at..at, line));
    }
    Ok((apply_edits(text, edits), name))
}

/// Replace the `key <name> { … };` entry of `xkb_symbols` with one carrying
/// `groups` (inserting it when the key has no entry yet). The key's other
/// explicit properties (`repeat=`, `vmods=`, and `actions[]` of groups that
/// still exist) are kept: Xorg leaves a key's explicit actions alone on a
/// mapping change (`XkbUpdateDescActions` skips `XkbExplicitInterpretMask`
/// keys), and the compiler derives everything else from the new keysyms.
/// No groups removes the symbols; the entry goes away if nothing else is left.
pub(crate) fn set_key(
    text: &str,
    name: &str,
    groups: &[KeyGroupSpec],
) -> Result<String, XkbEditError> {
    if groups.len() > MAX_GROUPS {
        return Err(XkbEditError::TooManyGroups(groups.len()));
    }
    for ty in groups.iter().filter_map(|g| g.type_name.as_deref()) {
        if ty.is_empty() || ty.chars().any(|c| c == '"' || c == '\\' || c.is_control()) {
            return Err(XkbEditError::BadTypeName(ty.to_owned()));
        }
    }
    let canonical = canonical_key_name(text, name)?;
    let body = section(text, "xkb_symbols")?;
    let stmts = statements(text, body.clone(), "xkb_symbols")?;
    let existing = stmts
        .iter()
        .find(|r| key_stmt_name(&text[(*r).clone()]) == Some(canonical.as_str()))
        .cloned();

    let (kept, actions) = match &existing {
        Some(r) => kept_key_fields(&text[r.clone()], groups.len())?,
        None => (Vec::new(), Vec::new()),
    };
    let entry = render_key(&canonical, &kept, groups, &actions);

    let edit = match existing {
        Some(r) => (line_extent(text, r), entry),
        None => {
            let at = stmts
                .iter()
                .find(|r| is_modifier_map(&text[(*r).clone()]))
                .map_or(body.end, |r| line_extent(text, r.clone()).start);
            if !entry.is_empty() && !text[..at].ends_with('\n') {
                (at..at, format!("\n{entry}"))
            } else {
                (at..at, entry)
            }
        }
    };
    Ok(apply_edits(text, vec![edit]))
}

/// Rewrite every `modifier_map` statement of `xkb_symbols` from a per-keycode
/// real-modifier mask (Xorg's `xkb->map->modmap`; bit 0 Shift … bit 7 Mod5).
/// Keycodes with bits set and no name get one ([`ensure_keycode_name`]).
/// A keycode in several modifiers is refused: the compiler keeps only one
/// modifier per key, so writing it would silently lose the others.
pub(crate) fn set_modifier_map(text: &str, modmap: &[u8; 256]) -> Result<String, XkbEditError> {
    if let Some(kc) = (0..=255u8).find(|&kc| modmap[usize::from(kc)].count_ones() > 1) {
        return Err(XkbEditError::MultipleModifiers(kc));
    }
    let mut text = text.to_owned();
    let mut names: Vec<(u8, String)> = Vec::new();
    for kc in 0..=255u8 {
        if modmap[usize::from(kc)] == 0 {
            continue;
        }
        let (named, name) = ensure_keycode_name(&text, kc)?;
        text = named;
        names.push((kc, name));
    }

    let body = section(&text, "xkb_symbols")?;
    let stmts = statements(&text, body.clone(), "xkb_symbols")?;
    let mut edits: Vec<(Range<usize>, String)> = stmts
        .iter()
        .filter(|r| is_modifier_map(&text[(*r).clone()]))
        .map(|r| (line_extent(&text, r.clone()), String::new()))
        .collect();

    let mut block = String::new();
    for (bit, mod_name) in REAL_MOD_NAMES.iter().enumerate() {
        let keys: Vec<String> = names
            .iter()
            .filter(|(kc, _)| modmap[usize::from(*kc)] & (1 << bit) != 0)
            .map(|(_, n)| format!("<{n}>"))
            .collect();
        if !keys.is_empty() {
            block.push_str(&format!(
                "\tmodifier_map {mod_name} {{ {} }};\n",
                keys.join(", ")
            ));
        }
    }
    if !block.is_empty() {
        let at = body.end;
        if !text[..at].ends_with('\n') {
            block.insert(0, '\n');
        }
        edits.push((at..at, block));
    }
    Ok(apply_edits(&text, edits))
}

// ─── writing ────────────────────────────────────────────────────────

/// A key entry in the serializer's layout; empty when there's nothing to say.
fn render_key(name: &str, kept: &[&str], groups: &[KeyGroupSpec], actions: &[&str]) -> String {
    let mut fields: Vec<String> = kept.iter().map(|f| (*f).to_owned()).collect();
    for (g, group) in groups.iter().enumerate() {
        if let Some(ty) = &group.type_name {
            fields.push(format!("type[{}]= \"{ty}\"", g + 1));
        }
    }
    for (g, group) in groups.iter().enumerate() {
        let syms: Vec<String> = if group.keysyms.is_empty() {
            vec!["NoSymbol".to_owned()]
        } else {
            group.keysyms.iter().map(|&s| keysym_text(s)).collect()
        };
        fields.push(format!("symbols[{}]= [ {} ]", g + 1, syms.join(", ")));
    }
    fields.extend(actions.iter().map(|a| (*a).to_owned()));
    if fields.is_empty() {
        return String::new();
    }
    format!("\tkey <{name}> {{\n\t\t{}\n\t}};\n", fields.join(",\n\t\t"))
}

/// A keysym as every libxkbcommon parses it. Hex is read as the keysym value
/// for anything from 10 up; the integers 0–9 would parse as the digit keysyms
/// `0`–`9`, and values above `XKB_KEYSYM_MAX` are rejected, so those (none of
/// which is an assigned keysym) are written as `NoSymbol`.
fn keysym_text(sym: u32) -> String {
    match sym {
        0 => "NoSymbol".to_owned(),
        1..=9 => {
            log::warn!("xkb edit: keysym {sym:#x} can't be written in keymap text; NoSymbol");
            "NoSymbol".to_owned()
        }
        s if s > KEYSYM_MAX => {
            log::warn!("xkb edit: keysym {s:#x} is out of range; NoSymbol");
            "NoSymbol".to_owned()
        }
        s => format!("{s:#x}"),
    }
}

/// The fields of an existing key entry that survive a rewrite: everything but
/// its types and symbols, with `actions[]` kept only for groups `< n_groups`.
/// Returns (other fields, action fields).
fn kept_key_fields(stmt: &str, n_groups: usize) -> Result<(Vec<&str>, Vec<&str>), XkbEditError> {
    let open = stmt
        .find('{')
        .ok_or(XkbEditError::Malformed("xkb_symbols"))?;
    let close =
        matching_close(stmt.as_bytes(), open).ok_or(XkbEditError::Malformed("xkb_symbols"))?;
    let mut kept = Vec::new();
    let mut actions = Vec::new();
    for field in split_top_level(&stmt[open + 1..close], b',') {
        let keyword = field
            .split(|c: char| c == '[' || c == '=' || c.is_whitespace())
            .next()
            .unwrap_or_default();
        if keyword.is_empty()
            || keyword.eq_ignore_ascii_case("symbols")
            || keyword.eq_ignore_ascii_case("type")
        {
            // `[ … ]` shorthand, `symbols[N]=`, `type=` / `type[N]=`.
            continue;
        }
        if keyword.eq_ignore_ascii_case("actions") {
            let group = field[keyword.len()..]
                .trim_start()
                .strip_prefix('[')
                .and_then(|t| t.split_once(']'))
                .map_or(Some(1), |(g, _)| group_index(g));
            if group.is_some_and(|g| g >= 1 && g <= n_groups) {
                actions.push(field);
            }
            continue;
        }
        kept.push(field);
    }
    Ok((kept, actions))
}

/// `1`, `Group1`, `group 1` → 1.
fn group_index(s: &str) -> Option<usize> {
    let s = s.trim();
    let digits = if s.len() >= 5 && s[..5].eq_ignore_ascii_case("group") {
        s[5..].trim()
    } else {
        s
    };
    digits.parse().ok()
}

/// Apply non-overlapping `(range, replacement)` edits to `text`.
fn apply_edits(text: &str, mut edits: Vec<(Range<usize>, String)>) -> String {
    edits.sort_by_key(|(r, _)| (r.start, r.end));
    let mut out = String::with_capacity(text.len() + 256);
    let mut pos = 0;
    for (r, rep) in edits {
        out.push_str(&text[pos..r.start]);
        out.push_str(&rep);
        pos = r.end;
    }
    out.push_str(&text[pos..]);
    out
}

// ─── reading ────────────────────────────────────────────────────────

/// The byte range between the braces of the section `keyword` opens.
fn section(text: &str, keyword: &'static str) -> Result<Range<usize>, XkbEditError> {
    let start = text
        .match_indices(keyword)
        .map(|(i, _)| i)
        .find(|&i| {
            (i == 0 || text.as_bytes()[i - 1] == b'\n')
                && text[i + keyword.len()..]
                    .chars()
                    .next()
                    .is_some_and(|c| c.is_whitespace() || c == '"' || c == '{')
        })
        .ok_or(XkbEditError::MissingSection(keyword))?;
    let open = start
        + text[start..]
            .find('{')
            .ok_or(XkbEditError::Malformed(keyword))?;
    let close = matching_close(text.as_bytes(), open).ok_or(XkbEditError::Malformed(keyword))?;
    Ok(open + 1..close)
}

/// The top-level statements of a section body, each from its first non-blank
/// byte to just past its `;`.
fn statements(
    text: &str,
    body: Range<usize>,
    section: &'static str,
) -> Result<Vec<Range<usize>>, XkbEditError> {
    let bytes = text.as_bytes();
    let mut out = Vec::new();
    let mut i = body.start;
    loop {
        while i < body.end && bytes[i].is_ascii_whitespace() {
            i += 1;
        }
        if i >= body.end {
            return Ok(out);
        }
        let start = i;
        let mut depth = 0usize;
        loop {
            if i >= body.end {
                return Err(XkbEditError::Malformed(section));
            }
            match bytes[i] {
                b'"' => {
                    i = skip_string(bytes, i).ok_or(XkbEditError::Malformed(section))?;
                    continue;
                }
                b'{' | b'[' | b'(' => depth += 1,
                b'}' | b']' | b')' => {
                    depth = depth
                        .checked_sub(1)
                        .ok_or(XkbEditError::Malformed(section))?;
                }
                b';' if depth == 0 => break,
                _ => {}
            }
            i += 1;
        }
        i += 1;
        out.push(start..i);
    }
}

/// Index of the `}` closing the `{` at `open`.
fn matching_close(bytes: &[u8], open: usize) -> Option<usize> {
    let mut depth = 0usize;
    let mut i = open;
    while i < bytes.len() {
        match bytes[i] {
            b'"' => {
                i = skip_string(bytes, i)?;
                continue;
            }
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
        i += 1;
    }
    None
}

/// Index just past the string literal that opens at `open`.
fn skip_string(bytes: &[u8], open: usize) -> Option<usize> {
    let mut i = open + 1;
    while i < bytes.len() {
        match bytes[i] {
            b'\\' => i += 2,
            b'"' => return Some(i + 1),
            _ => i += 1,
        }
    }
    None
}

/// Split at top-level `sep`, trimmed, empty pieces dropped.
fn split_top_level(s: &str, sep: u8) -> Vec<&str> {
    let bytes = s.as_bytes();
    let mut out = Vec::new();
    let mut depth = 0usize;
    let mut start = 0;
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'"' => {
                i = skip_string(bytes, i).unwrap_or(bytes.len());
                continue;
            }
            b'{' | b'[' | b'(' => depth += 1,
            b'}' | b']' | b')' => depth = depth.saturating_sub(1),
            c if c == sep && depth == 0 => {
                out.push(s[start..i].trim());
                start = i + 1;
            }
            _ => {}
        }
        i += 1;
    }
    out.push(s[start..].trim());
    out.retain(|p| !p.is_empty());
    out
}

/// The whole lines a statement occupies: back to the start of its line and
/// forward over its line break, so removing it leaves no blank line.
fn line_extent(text: &str, r: Range<usize>) -> Range<usize> {
    let bytes = text.as_bytes();
    let mut start = r.start;
    while start > 0 && matches!(bytes[start - 1], b' ' | b'\t') {
        start -= 1;
    }
    let mut end = r.end;
    while end < bytes.len() && matches!(bytes[end], b' ' | b'\t') {
        end += 1;
    }
    if end < bytes.len() && bytes[end] == b'\n' {
        end += 1;
    }
    start..end
}

/// `<NAME> = 38;` → `("NAME", 38)`.
fn keycode_def(stmt: &str) -> Option<(&str, u32)> {
    let (name, rest) = stmt.strip_prefix('<')?.split_once('>')?;
    let value = rest
        .trim()
        .strip_prefix('=')?
        .trim()
        .strip_suffix(';')?
        .trim();
    Some((name, value.parse().ok()?))
}

/// `alias <A> = <B>;` → `("A", "B")`.
fn alias_pair(stmt: &str) -> Option<(&str, &str)> {
    let rest = stmt.strip_prefix("alias")?.trim_start();
    let (alias, rest) = rest.strip_prefix('<')?.split_once('>')?;
    let target = rest
        .trim()
        .strip_prefix('=')?
        .trim()
        .strip_prefix('<')?
        .split_once('>')?
        .0;
    Some((alias, target))
}

fn alias_def(stmt: &str) -> Option<&str> {
    alias_pair(stmt).map(|(a, _)| a)
}

/// `keyword = 8;` → 8.
fn assignment(stmt: &str, keyword: &str) -> Option<u32> {
    let rest = stmt.strip_prefix(keyword)?.trim_start().strip_prefix('=')?;
    rest.trim().strip_suffix(';')?.trim().parse().ok()
}

/// `key <NAME> { … };` → `NAME`.
fn key_stmt_name(stmt: &str) -> Option<&str> {
    let rest = stmt.strip_prefix("key")?;
    if !rest.starts_with(|c: char| c.is_whitespace()) {
        return None;
    }
    rest.trim_start()
        .strip_prefix('<')?
        .split_once('>')
        .map(|(n, _)| n)
}

fn is_modifier_map(stmt: &str) -> bool {
    stmt.strip_prefix("modifier_map")
        .is_some_and(|r| r.starts_with(|c: char| c.is_whitespace()))
}

/// The keycode name `name` stands for: itself, or an alias's target.
fn canonical_key_name(text: &str, name: &str) -> Result<String, XkbEditError> {
    let body = section(text, "xkb_keycodes")?;
    let mut alias_target = None;
    for r in statements(text, body, "xkb_keycodes")? {
        let stmt = &text[r];
        if keycode_def(stmt).is_some_and(|(n, _)| n == name) {
            return Ok(name.to_owned());
        }
        if let Some((a, t)) = alias_pair(stmt)
            && a == name
        {
            alias_target = Some(t.to_owned());
        }
    }
    alias_target.ok_or_else(|| XkbEditError::UnknownKey(name.to_owned()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::kms::xkb::{explicit_type_names, golden_keymap, keymap_modmap};
    use xkbcommon::xkb::{self, Keycode, Keymap};

    /// The four frozen fixtures, as `golden_keymap` keys them.
    const FIXTURES: [(&str, Option<&str>); 4] = [
        ("us", None),
        ("gb", None),
        ("de", None),
        ("us,ru", Some("grp:alt_shift_toggle")),
    ];

    /// What an edit operates on in production: xkbcommon's own V1 dump of
    /// the live keymap.
    fn dump(km: &Keymap) -> String {
        km.get_as_string(xkb::KEYMAP_FORMAT_TEXT_V1)
    }

    fn compile(text: &str) -> Keymap {
        let ctx = xkb::Context::new(xkb::CONTEXT_NO_FLAGS);
        Keymap::new_from_string(
            &ctx,
            text.to_owned(),
            xkb::KEYMAP_FORMAT_TEXT_V1,
            xkb::KEYMAP_COMPILE_NO_FLAGS,
        )
        .expect("edited keymap text must compile")
    }

    /// A key as clients see it, read back through xkbcommon: per group, per
    /// level, the keysyms and the modifier masks that select the level.
    #[derive(Debug, PartialEq, Eq)]
    struct KeySig {
        groups: Vec<Vec<(Vec<u32>, Vec<u32>)>>,
    }

    fn key_sig(km: &Keymap, kc: u32) -> KeySig {
        let key = Keycode::new(kc);
        let groups = (0..km.num_layouts_for_key(key))
            .map(|g| {
                (0..km.num_levels_for_key(key, g))
                    .map(|l| {
                        let syms = km
                            .key_get_syms_by_level(key, g, l)
                            .iter()
                            .map(|s| s.raw())
                            .collect();
                        let mut masks = [0u32; 64];
                        let n = km.key_get_mods_for_level(key, g, l, &mut masks);
                        let mut masks = masks[..n].to_vec();
                        masks.sort_unstable();
                        (syms, masks)
                    })
                    .collect()
            })
            .collect();
        KeySig { groups }
    }

    /// Every key but `except` reads back identically, repeat flag included.
    fn assert_untouched(before: &Keymap, after: &Keymap, except: &[u32]) {
        // xkbcommon's range follows the keycodes that exist, so naming
        // keycode 8 moves its minimum from 9 to 8: compare over both ranges.
        let lo = before.min_keycode().raw().min(after.min_keycode().raw());
        let hi = before.max_keycode().raw().max(after.max_keycode().raw());
        for kc in lo..=hi {
            if except.contains(&kc) {
                continue;
            }
            assert_eq!(
                key_sig(after, kc),
                key_sig(before, kc),
                "untouched keycode {kc} changed"
            );
            assert_eq!(
                after.key_repeats(Keycode::new(kc)),
                before.key_repeats(Keycode::new(kc)),
                "repeat flag of untouched keycode {kc} changed"
            );
        }
    }

    /// The spec that reproduces keycode `kc` of `km`: its keysyms per level
    /// and its explicit type names, both read from xkbcommon.
    fn spec_of(km: &Keymap, kc: u8) -> Vec<KeyGroupSpec> {
        let key = Keycode::new(u32::from(kc));
        let types = explicit_type_names(km).remove(&kc).unwrap_or_default();
        (0..km.num_layouts_for_key(key))
            .map(|g| KeyGroupSpec {
                type_name: types[g as usize].clone(),
                keysyms: (0..km.num_levels_for_key(key, g))
                    .map(|l| {
                        let syms = km.key_get_syms_by_level(key, g, l);
                        assert!(syms.len() <= 1, "source key {kc} has a multi-keysym level");
                        syms.first().map_or(0, |s| s.raw())
                    })
                    .collect(),
            })
            .collect()
    }

    #[test]
    fn keycode_name_matches_xkbcommon() {
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            let text = dump(&km);
            for kc in 8..=255u8 {
                assert_eq!(
                    keycode_name(&text, kc).expect("keycodes section"),
                    km.key_get_name(Keycode::new(u32::from(kc)))
                        .map(str::to_owned),
                    "{layout}: name of keycode {kc}"
                );
            }
        }
    }

    #[test]
    fn ensure_keycode_name_keeps_an_existing_name() {
        let km = golden_keymap("us", None);
        let text = dump(&km);
        let (out, name) = ensure_keycode_name(&text, 38).expect("named keycode");
        assert_eq!(Some(name.as_str()), km.key_get_name(Keycode::new(38)));
        assert_eq!(out, text, "a named keycode leaves the text as it was");
    }

    #[test]
    fn ensure_keycode_name_names_an_unnamed_keycode() {
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            assert_eq!(km.key_get_name(Keycode::new(8)), None, "precondition");
            let (out, name) = ensure_keycode_name(&dump(&km), 8).expect("names keycode 8");
            let after = compile(&out);
            assert_eq!(after.key_get_name(Keycode::new(8)), Some(name.as_str()));
            assert_eq!(after.key_by_name(&name).map(|k| k.raw()), Some(8));
            assert!(name.len() <= 4, "X key names are 4 bytes on the wire");
            for kc in 9..=before_max(&km) {
                assert_eq!(
                    after.key_get_name(Keycode::new(kc)),
                    km.key_get_name(Keycode::new(kc)),
                    "{layout}: name of keycode {kc}"
                );
            }
            assert_untouched(&km, &after, &[]);
        }
    }

    fn before_max(km: &Keymap) -> u32 {
        km.max_keycode().raw()
    }

    #[test]
    fn set_key_replaces_a_key_with_another_keys_definition() {
        // Source keys cover: explicit multi-level type (FK01 CTRL+ALT, 5
        // levels), KEYPAD (KPDL, two groups on us,ru), a non-default modifier
        // type (LFSH PC_ALT_LEVEL2), a plain alphabetic key (AD01) and a
        // four-level key (AE10 on de, AE08 group 2 on us,ru).
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            let text = dump(&km);
            for source in [67u8, 91, 50, 24, 19, 17] {
                let spec = spec_of(&km, source);
                let out = set_key(&text, "AC01", &spec).expect("set_key");
                let after = compile(&out);
                assert_eq!(
                    key_sig(&after, 38),
                    key_sig(&km, u32::from(source)),
                    "{layout}: <AC01> must now read back as keycode {source}"
                );
                assert_untouched(&km, &after, &[38]);
                assert_eq!(keymap_modmap(&after), keymap_modmap(&km), "modmap");
            }
        }
    }

    #[test]
    fn set_key_accepts_an_alias() {
        // <AC12> is an alias of <BKSL> in every fixture.
        let km = golden_keymap("us", None);
        let bksl = km.key_by_name("BKSL").expect("BKSL").raw();
        let spec = spec_of(&km, 38);
        let after = compile(&set_key(&dump(&km), "AC12", &spec).expect("alias"));
        assert_eq!(key_sig(&after, bksl), key_sig(&km, 38));
        assert_untouched(&km, &after, &[bksl]);
    }

    #[test]
    fn set_key_inserts_a_key_that_has_no_symbols() {
        let km = golden_keymap("us", None);
        assert_eq!(km.num_layouts_for_key(Keycode::new(248)), 0, "precondition");
        let spec = spec_of(&km, 240);
        let after = compile(&set_key(&dump(&km), "I248", &spec).expect("insert"));
        assert_eq!(key_sig(&after, 248), key_sig(&km, 240));
        assert_untouched(&km, &after, &[248]);
    }

    #[test]
    fn set_key_on_an_unnamed_keycode() {
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            let (named, name) = ensure_keycode_name(&dump(&km), 8).expect("name");
            let spec = spec_of(&km, 38);
            let after = compile(&set_key(&named, &name, &spec).expect("set"));
            assert_eq!(key_sig(&after, 8), key_sig(&km, 38), "{layout}");
            assert_untouched(&km, &after, &[8]);
        }
    }

    #[test]
    fn set_key_without_groups_clears_the_key() {
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            let after = compile(&set_key(&dump(&km), "AC01", &[]).expect("clear"));
            assert_eq!(after.num_layouts_for_key(Keycode::new(38)), 0, "{layout}");
            assert_untouched(&km, &after, &[38]);
        }
    }

    #[test]
    fn set_key_keeps_explicit_repeat_vmods_and_actions() {
        // Give <CAPS> explicit properties the fixtures don't carry, and take
        // xkbcommon's own dump of that as the input, so the input is in the
        // serializer's format.
        let km = golden_keymap("us", None);
        let text = dump(&km);
        let caps = "\tkey <CAPS> {\t[ 0xffe5 ] };\n";
        assert!(text.contains(caps), "fixture shape");
        let crafted = text.replace(
            caps,
            "\tkey <CAPS> {\n\t\trepeat= No,\n\t\tvmods= NumLock,\n\t\t\
             symbols[1]= [ 0xffe5 ],\n\t\tactions[1]= [ LockMods(modifiers=Mod3) ]\n\t};\n",
        );
        let before = compile(&dump(&compile(&crafted)));
        let input = dump(&before);
        assert!(input.contains("repeat= No") || input.contains("repeat=No"));
        assert!(input.contains("actions[1]"), "explicit action is dumped");

        // Rebind the key to Control_L: the interpret for Control_L would give
        // SetMods(Control), but the explicit LockMods(Mod3) must survive.
        let spec = [KeyGroupSpec {
            type_name: None,
            keysyms: vec![0xffe3],
        }];
        let after = compile(&set_key(&input, "CAPS", &spec).expect("set"));
        let caps_kc = Keycode::new(66);
        assert_eq!(after.key_get_syms_by_level(caps_kc, 0, 0)[0].raw(), 0xffe3);
        assert_eq!(after.key_repeats(caps_kc), before.key_repeats(caps_kc));
        assert!(!after.key_repeats(caps_kc));
        let locked = |k: &Keymap| {
            let mut st = xkb::State::new(k);
            st.update_key(caps_kc, xkb::KeyDirection::Down);
            st.update_key(caps_kc, xkb::KeyDirection::Up);
            st.serialize_mods(xkb::STATE_MODS_LOCKED)
        };
        assert_ne!(locked(&before), 0, "precondition: the action locks");
        assert_eq!(locked(&after), locked(&before), "explicit action kept");
        assert_untouched(&before, &after, &[66]);
    }

    #[test]
    fn set_key_rejects_what_it_cannot_express() {
        let text = dump(&golden_keymap("us", None));
        let one = KeyGroupSpec {
            type_name: None,
            keysyms: vec![0x61],
        };
        assert!(set_key(&text, "NOPE", std::slice::from_ref(&one)).is_err());
        assert!(set_key(&text, "AC01", &vec![one.clone(); 5]).is_err());
        let bad_type = KeyGroupSpec {
            type_name: Some("A\"B".into()),
            keysyms: vec![0x61],
        };
        assert!(set_key(&text, "AC01", &[bad_type]).is_err());
    }

    #[test]
    fn set_modifier_map_round_trips() {
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            // Headline xmodmap case: Caps from Lock to Control.
            let mut modmap = keymap_modmap(&km);
            assert_eq!(modmap[66], 0x02, "{layout}: precondition CAPS in Lock");
            modmap[66] = 0x04;
            let after = compile(&set_modifier_map(&dump(&km), &modmap).expect("modmap"));
            assert_eq!(keymap_modmap(&after), modmap, "{layout}");
            for kc in 8..=255 {
                assert_eq!(key_sig(&after, kc), key_sig(&km, kc), "{layout}: {kc}");
            }
        }
    }

    #[test]
    fn set_modifier_map_can_clear_everything() {
        let km = golden_keymap("de", None);
        let out = set_modifier_map(&dump(&km), &[0u8; 256]).expect("modmap");
        assert!(!out.contains("modifier_map"));
        assert_eq!(keymap_modmap(&compile(&out)), [0u8; 256]);
    }

    /// xkbcommon (like xkbcomp) keeps one modifier per key in its modmap: a
    /// key listed under two `modifier_map`s ends up in the last one only.
    /// The core modmap allows several, so such a map can't go through the
    /// text and must be refused, not silently collapsed.
    #[test]
    fn set_modifier_map_refuses_a_key_in_two_modifiers() {
        let km = golden_keymap("us", None);
        let mut modmap = keymap_modmap(&km);
        modmap[50] |= 0x20; // LFSH: Shift and Mod3
        let collapsed = {
            let mut text = dump(&km);
            text = text.replace(
                "\tmodifier_map Mod3 { <LVL5> };",
                "\tmodifier_map Mod3 { <LVL5>, <LFSH> };",
            );
            keymap_modmap(&compile(&text))[50]
        };
        assert_eq!(
            collapsed.count_ones(),
            1,
            "xkbcommon collapses to one modifier"
        );
        assert_eq!(
            set_modifier_map(&dump(&km), &modmap),
            Err(XkbEditError::MultipleModifiers(50))
        );
    }

    #[test]
    fn set_modifier_map_names_an_unnamed_keycode() {
        let km = golden_keymap("us", None);
        let (named, name) = ensure_keycode_name(&dump(&km), 8).expect("name");
        let spec = spec_of(&km, 133); // LWIN
        let with_key = set_key(&named, &name, &spec).expect("set");
        let mut modmap = keymap_modmap(&km);
        modmap[8] = 0x20; // Mod3
        let text = set_modifier_map(&with_key, &modmap).expect("modmap");
        assert_eq!(keymap_modmap(&compile(&text)), modmap);

        // Without a prior name, set_modifier_map names the keycode itself.
        let mut modmap2 = keymap_modmap(&km);
        modmap2[8] = 0x20;
        let out2 = set_modifier_map(&dump(&km), &modmap2).expect("modmap");
        let after2 = compile(&out2);
        assert!(after2.key_get_name(Keycode::new(8)).is_some());
        assert_eq!(keymap_modmap(&after2), modmap2);
    }
}
