//! Edits over xkbcommon's V1 keymap dump (#171).
//!
//! xkbcommon keymaps are immutable and expose no structured access to types,
//! actions or behaviors, so a runtime mapping change (ChangeKeyboardMapping,
//! SetModifierMapping) takes the live keymap's complete V1 dump
//! ([`keymap_text`]), edits it here, and hands the result
//! to [`crate::kms::core::KmsCore::install_keymap_text`]. The compiler then
//! re-derives actions and the vmodmap from the compat interprets, which is what
//! Xorg's `XkbUpdateDescActions` does after `XkbUpdateKeyTypesFromCore`.
//!
//! The input is machine-generated by xkbcommon's serializer, and the parser
//! relies on that shape: sections open at the start of a line
//! (`xkb_keycodes "…" {`, `xkb_symbols "…" {`), every statement ends in `;`,
//! strings are double-quoted, and there are no comments. Braces, brackets and
//! strings are still matched properly, so nested `{ … }` (multi-keysym levels)
//! and bracketed lists never confuse a statement boundary.

use std::{collections::HashSet, fmt, ops::Range};

use crate::kms::xkb::REAL_MOD_NAMES;

/// The live keymap as V1 text with nothing left out: what every edit starts
/// from and every derivation reads.
///
/// libxkbcommon 1.12+ drops the key types and compat entries no key uses
/// from `xkb_keymap_get_as_string` (unless asked with
/// `XKB_KEYMAP_SERIALIZE_KEEP_UNUSED` through `xkb_keymap_get_as_string2`).
/// An edit compiled from such text loses those interprets for good, although
/// a later mapping change may need them: Xorg keeps its whole compat map, so
/// after `keycode 66 = Control_L` a key still in Lock matches
/// `Any+Exactly(Lock)` (LockMods), which the trimmed text no longer has. The
/// `xkbcommon` crate predates the call, so it is looked up at run time;
/// older libraries have no such trimming and their plain dump is complete.
pub(crate) fn keymap_text(keymap: &xkbcommon::xkb::Keymap) -> String {
    type GetAsString2 = unsafe extern "C" fn(
        *mut xkbcommon::xkb::ffi::xkb_keymap,
        std::ffi::c_int,
        std::ffi::c_int,
    ) -> *mut std::ffi::c_char;
    /// `XKB_KEYMAP_FORMAT_TEXT_V1`, `XKB_KEYMAP_SERIALIZE_KEEP_UNUSED`.
    const FORMAT_TEXT_V1: std::ffi::c_int = 1;
    const SERIALIZE_KEEP_UNUSED: std::ffi::c_int = 1 << 1;
    static GET_AS_STRING2: std::sync::OnceLock<Option<GetAsString2>> = std::sync::OnceLock::new();
    let get = GET_AS_STRING2.get_or_init(|| {
        // SAFETY: dlsym with RTLD_DEFAULT and a NUL-terminated name only
        // looks the symbol up; a non-null result is libxkbcommon's
        // `xkb_keymap_get_as_string2`, whose C signature `GetAsString2` is.
        let sym = unsafe { libc::dlsym(libc::RTLD_DEFAULT, c"xkb_keymap_get_as_string2".as_ptr()) };
        (!sym.is_null()).then(|| {
            // SAFETY: see above; same size, it's a function pointer.
            unsafe { std::mem::transmute::<*mut std::ffi::c_void, GetAsString2>(sym) }
        })
    });
    if let Some(get) = get {
        // SAFETY: the keymap pointer is live for the borrow; the result is a
        // malloc'd NUL-terminated string (or NULL) that we own and free.
        unsafe {
            let raw = get(keymap.get_raw_ptr(), FORMAT_TEXT_V1, SERIALIZE_KEEP_UNUSED);
            if !raw.is_null() {
                let text = std::ffi::CStr::from_ptr(raw).to_string_lossy().into_owned();
                libc::free(raw.cast());
                return text;
            }
        }
    }
    keymap.get_as_string(xkbcommon::xkb::KEYMAP_FORMAT_TEXT_V1)
}

/// `XkbNumKbdGroups`: a key has at most four groups.
const MAX_GROUPS: usize = 4;

/// `XKB_KEYSYM_MAX`: the largest keysym libxkbcommon accepts.
const KEYSYM_MAX: u32 = 0x1fff_ffff;

/// One group of a key as a runtime mapping change describes it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct KeyGroupSpec {
    /// Explicit key type; `None` lets the compiler pick one from the keysyms.
    pub type_name: Option<String>,
    /// One keysym per shift level, level 1 first; `0` is `NoSymbol`.
    pub keysyms: Vec<u32>,
}

/// Why an edit of the keymap text was refused. The text is left unchanged.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum XkbEditError {
    /// The text has no `xkb_keycodes` / `xkb_symbols` section.
    MissingSection(&'static str),
    /// A brace, bracket or string in the named section doesn't close.
    Malformed(&'static str),
    /// The key name is neither a keycode name nor an alias.
    UnknownKey(String),
    /// More groups than XKB allows.
    TooManyGroups(usize),
    /// A type name that can't be written as an XKB string.
    BadTypeName(String),
    /// Keycodes below 8 don't exist in X.
    InvalidKeycode(u8),
    /// Every candidate name for the keycode is already taken.
    NoFreeKeyName(u8),
    /// The keycode is in more than one modifier; keymap text keeps one per
    /// key (xkbcommon and xkbcomp both drop all but the last).
    MultipleModifiers(u8),
}

impl fmt::Display for XkbEditError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingSection(s) => write!(f, "keymap text has no {s} section"),
            Self::Malformed(s) => write!(f, "unbalanced brace, bracket or string in {s}"),
            Self::UnknownKey(k) => write!(f, "no key named <{k}>"),
            Self::TooManyGroups(n) => write!(f, "{n} groups (XKB allows {MAX_GROUPS})"),
            Self::BadTypeName(t) => write!(f, "type name {t:?} can't be written"),
            Self::InvalidKeycode(kc) => write!(f, "keycode {kc} is below the X minimum of 8"),
            Self::NoFreeKeyName(kc) => write!(f, "no free key name for keycode {kc}"),
            Self::MultipleModifiers(kc) => {
                write!(
                    f,
                    "keycode {kc} is in several modifiers; XKB text allows one"
                )
            }
        }
    }
}

impl std::error::Error for XkbEditError {}

/// Make sure `keycode` has a name in `xkb_keycodes`, adding `<Innn> = nnn;`
/// when it has none (ChangeKeyboardMapping and SetModifierMapping may target
/// a keycode the keymap never named). Returns the text and the name.
pub(crate) fn ensure_keycode_name(
    text: &str,
    keycode: u8,
) -> Result<(String, String), XkbEditError> {
    if keycode < 8 {
        return Err(XkbEditError::InvalidKeycode(keycode));
    }
    let body = section(text, "xkb_keycodes")?;
    let stmts = statements(text, body.clone(), "xkb_keycodes")?;
    let mut taken = HashSet::new();
    let mut last_def: Option<Range<usize>> = None;
    let mut minimum: Option<(Range<usize>, u32)> = None;
    let mut maximum: Option<(Range<usize>, u32)> = None;
    for r in &stmts {
        let stmt = &text[r.clone()];
        if let Some((name, kc)) = keycode_def(stmt) {
            if kc == u32::from(keycode) {
                return Ok((text.to_owned(), name.to_owned()));
            }
            taken.insert(name.to_owned());
            last_def = Some(r.clone());
        } else if let Some(alias) = alias_def(stmt) {
            taken.insert(alias.to_owned());
        } else if let Some(v) = assignment(stmt, "minimum") {
            minimum = Some((r.clone(), v));
        } else if let Some(v) = assignment(stmt, "maximum") {
            maximum = Some((r.clone(), v));
        }
    }
    // Four characters at most: key names are 4 bytes on the X wire.
    let name = ['I', 'J', 'K', 'L']
        .iter()
        .map(|p| format!("{p}{keycode:03}"))
        .find(|n| !taken.contains(n))
        .ok_or(XkbEditError::NoFreeKeyName(keycode))?;

    let kc = u32::from(keycode);
    let mut edits: Vec<(Range<usize>, String)> = Vec::new();
    if let Some((r, v)) = minimum
        && kc < v
    {
        edits.push((r, format!("minimum = {kc};")));
    }
    if let Some((r, v)) = maximum
        && kc > v
    {
        edits.push((r, format!("maximum = {kc};")));
    }
    let line = format!("\t<{name}> = {kc};\n");
    let at = last_def.map_or(body.start, |r| line_extent(text, r).end);
    if at == body.start && !text[..at].ends_with('\n') {
        edits.push((at..at, format!("\n{line}")));
    } else {
        edits.push((at..at, line));
    }
    Ok((apply_edits(text, edits), name))
}

/// Replace the `key <name> { … };` entry of `xkb_symbols` with one carrying
/// `groups` (inserting it when the key has no entry yet). The key's other
/// explicit properties (`repeat=`, `vmods=`, and `actions[]` of groups that
/// still exist) are kept: Xorg leaves a key's explicit actions alone on a
/// mapping change (`XkbUpdateDescActions` skips `XkbExplicitInterpretMask`
/// keys), and the compiler derives everything else from the new keysyms.
/// No groups removes the symbols; the entry goes away if nothing else is left.
pub(crate) fn set_key(
    text: &str,
    name: &str,
    groups: &[KeyGroupSpec],
) -> Result<String, XkbEditError> {
    if groups.len() > MAX_GROUPS {
        return Err(XkbEditError::TooManyGroups(groups.len()));
    }
    for ty in groups.iter().filter_map(|g| g.type_name.as_deref()) {
        if ty.is_empty() || ty.chars().any(|c| c == '"' || c == '\\' || c.is_control()) {
            return Err(XkbEditError::BadTypeName(ty.to_owned()));
        }
    }
    let canonical = canonical_key_name(text, name)?;
    let body = section(text, "xkb_symbols")?;
    let stmts = statements(text, body.clone(), "xkb_symbols")?;
    let existing = stmts
        .iter()
        .find(|r| key_stmt_name(&text[(*r).clone()]) == Some(canonical.as_str()))
        .cloned();

    let (kept, actions) = match &existing {
        Some(r) => kept_key_fields(&text[r.clone()], groups.len())?,
        None => (Vec::new(), Vec::new()),
    };
    let entry = render_key(&canonical, &kept, groups, &actions);

    let edit = match existing {
        Some(r) => (line_extent(text, r), entry),
        None => {
            let at = stmts
                .iter()
                .find(|r| is_modifier_map(&text[(*r).clone()]))
                .map_or(body.end, |r| line_extent(text, r.clone()).start);
            if !entry.is_empty() && !text[..at].ends_with('\n') {
                (at..at, format!("\n{entry}"))
            } else {
                (at..at, entry)
            }
        }
    };
    Ok(apply_edits(text, vec![edit]))
}

/// Rewrite every `modifier_map` statement of `xkb_symbols` from a per-keycode
/// real-modifier mask (Xorg's `xkb->map->modmap`; bit 0 Shift … bit 7 Mod5).
/// Keycodes with bits set and no name get one ([`ensure_keycode_name`]).
/// A keycode in several modifiers is refused: the compiler keeps only one
/// modifier per key, so writing it would silently lose the others.
pub(crate) fn set_modifier_map(text: &str, modmap: &[u8; 256]) -> Result<String, XkbEditError> {
    if let Some(kc) = (0..=255u8).find(|&kc| modmap[usize::from(kc)].count_ones() > 1) {
        return Err(XkbEditError::MultipleModifiers(kc));
    }
    let mut text = text.to_owned();
    let mut names: Vec<(u8, String)> = Vec::new();
    for kc in 0..=255u8 {
        if modmap[usize::from(kc)] == 0 {
            continue;
        }
        let (named, name) = ensure_keycode_name(&text, kc)?;
        text = named;
        names.push((kc, name));
    }

    let body = section(&text, "xkb_symbols")?;
    let stmts = statements(&text, body.clone(), "xkb_symbols")?;
    let mut edits: Vec<(Range<usize>, String)> = stmts
        .iter()
        .filter(|r| is_modifier_map(&text[(*r).clone()]))
        .map(|r| (line_extent(&text, r.clone()), String::new()))
        .collect();

    let mut block = String::new();
    for (bit, mod_name) in REAL_MOD_NAMES.iter().enumerate() {
        let keys: Vec<String> = names
            .iter()
            .filter(|(kc, _)| modmap[usize::from(*kc)] & (1 << bit) != 0)
            .map(|(_, n)| format!("<{n}>"))
            .collect();
        if !keys.is_empty() {
            block.push_str(&format!(
                "\tmodifier_map {mod_name} {{ {} }};\n",
                keys.join(", ")
            ));
        }
    }
    if !block.is_empty() {
        let at = body.end;
        if !text[..at].ends_with('\n') {
            block.insert(0, '\n');
        }
        edits.push((at..at, block));
    }
    Ok(apply_edits(&text, edits))
}

/// The names of the key types `xkb_types` defines, in definition order.
pub(crate) fn type_names(text: &str) -> Result<Vec<String>, XkbEditError> {
    let body = section(text, "xkb_types")?;
    Ok(statements(text, body, "xkb_types")?
        .into_iter()
        .filter_map(|r| {
            let rest = text[r].strip_prefix("type")?;
            if !rest.starts_with(|c: char| c.is_whitespace()) {
                return None;
            }
            rest.trim_start()
                .strip_prefix('"')?
                .split_once('"')
                .map(|(n, _)| n.to_owned())
        })
        .collect())
}

/// `text` plus one probe key per type in `names`: a new keycode above every
/// existing one whose single group has that type (the keysym is
/// `VoidSymbol`). xkbcommon exposes no key's type name, but compiling this
/// shows what each named type does (its levels and the modifiers selecting
/// them), which identifies the type a key got implicitly. Returns the text
/// and the probes' keycodes, in `names` order. Never installed.
pub(crate) fn add_type_probes(
    text: &str,
    names: &[String],
) -> Result<(String, Vec<u32>), XkbEditError> {
    let body = section(text, "xkb_keycodes")?;
    let mut taken = HashSet::new();
    let mut top = 0u32;
    let mut last_def: Option<Range<usize>> = None;
    let mut maximum: Option<Range<usize>> = None;
    for r in statements(text, body.clone(), "xkb_keycodes")? {
        let stmt = &text[r.clone()];
        if let Some((name, kc)) = keycode_def(stmt) {
            taken.insert(name.to_owned());
            top = top.max(kc);
            last_def = Some(r);
        } else if let Some(alias) = alias_def(stmt) {
            taken.insert(alias.to_owned());
        } else if let Some(v) = assignment(stmt, "maximum") {
            top = top.max(v);
            maximum = Some(r);
        }
    }
    let mut probes = Vec::with_capacity(names.len());
    let mut defs = String::new();
    let mut n = 0usize;
    for _ in names {
        let name = loop {
            let candidate = format!("TPRB{n}");
            n += 1;
            if !taken.contains(&candidate) {
                break candidate;
            }
        };
        let kc = top + 1 + u32::try_from(probes.len()).unwrap_or(u32::MAX);
        defs.push_str(&format!("\t<{name}> = {kc};\n"));
        probes.push((name, kc));
    }
    let mut edits: Vec<(Range<usize>, String)> = Vec::new();
    if let (Some(r), Some((_, kc))) = (maximum, probes.last()) {
        edits.push((r, format!("maximum = {kc};")));
    }
    let at = last_def.map_or(body.start, |r| line_extent(text, r).end);
    if at == body.start && !text[..at].ends_with('\n') {
        defs.insert(0, '\n');
    }
    edits.push((at..at, defs));
    let text = apply_edits(text, edits);

    let body = section(&text, "xkb_symbols")?;
    let stmts = statements(&text, body.clone(), "xkb_symbols")?;
    let mut entries = String::new();
    for ((name, _), ty) in probes.iter().zip(names) {
        let group = KeyGroupSpec {
            type_name: Some(ty.clone()),
            keysyms: vec![0x00ff_ffff], // VoidSymbol
        };
        entries.push_str(&render_key(name, &[], std::slice::from_ref(&group), &[]));
    }
    let at = stmts
        .iter()
        .find(|r| is_modifier_map(&text[(*r).clone()]))
        .map_or(body.end, |r| line_extent(&text, r.clone()).start);
    if !text[..at].ends_with('\n') {
        entries.insert(0, '\n');
    }
    let text = apply_edits(&text, vec![(at..at, entries)]);
    Ok((text, probes.into_iter().map(|(_, kc)| kc).collect()))
}

/// Rewrite the explicit real-modifier mapping of virtual modifiers in every
/// `virtual_modifiers` statement (each section declares its own). For each
/// `(name, mapping)`: `Some(mask)` with a non-zero mask writes
/// `Name=Mod1+…`, anything else writes a bare `Name`, which leaves the
/// mapping to the compiler (the modmap of the keys whose vmodmap names the
/// vmod). Virtual modifiers not listed keep their declaration.
///
/// xkbcommon ORs an explicit mapping with the derived one, so an explicit
/// mapping is only exact for a virtual modifier no key's vmodmap names.
pub(crate) fn set_virtual_modifier_mappings(
    text: &str,
    mappings: &[(String, Option<u8>)],
) -> Result<String, XkbEditError> {
    let mut edits = Vec::new();
    for keyword in ["xkb_types", "xkb_compatibility", "xkb_symbols"] {
        let Ok(body) = section(text, keyword) else {
            continue;
        };
        for r in statements(text, body, keyword)? {
            let stmt = &text[r.clone()];
            let Some(rest) = stmt.strip_prefix("virtual_modifiers") else {
                continue;
            };
            if !rest.starts_with(|c: char| c.is_whitespace()) {
                continue;
            }
            let list = rest.trim().trim_end_matches(';');
            let items: Vec<String> = split_top_level(list, b',')
                .into_iter()
                .map(|item| {
                    let name = item.split('=').next().unwrap_or_default().trim();
                    match mappings.iter().find(|(n, _)| n == name) {
                        Some((_, Some(mask))) if *mask != 0 => {
                            let mods: Vec<&str> = REAL_MOD_NAMES
                                .iter()
                                .enumerate()
                                .filter(|(bit, _)| mask & (1 << bit) != 0)
                                .map(|(_, n)| *n)
                                .collect();
                            format!("{name}={}", mods.join("+"))
                        }
                        Some(_) => name.to_owned(),
                        None => item.to_owned(),
                    }
                })
                .collect();
            edits.push((r, format!("virtual_modifiers {};", items.join(","))));
        }
    }
    Ok(apply_edits(text, edits))
}

/// One `interpret` statement of `xkb_compatibility`, split but not
/// interpreted: `head` is `Keysym+Match(mods)`, `fields` its body's
/// statements (`virtualModifier= Meta`, `action= SetMods(…)`, …).
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct InterpretText {
    pub head: String,
    pub fields: Vec<String>,
}

/// `(interprets, defaults)` of [`interpret_texts`].
pub(crate) type InterpretTexts = (Vec<InterpretText>, Vec<(String, String)>);

/// The `interpret` statements of `xkb_compatibility` in order, plus the
/// `interpret.field= value` defaults that precede them (as `(field, value)`).
pub(crate) fn interpret_texts(text: &str) -> Result<InterpretTexts, XkbEditError> {
    let body = section(text, "xkb_compatibility")?;
    let mut interprets = Vec::new();
    let mut defaults = Vec::new();
    for r in statements(text, body, "xkb_compatibility")? {
        let stmt = &text[r];
        let Some(rest) = stmt.strip_prefix("interpret") else {
            continue;
        };
        if let Some(default) = rest.strip_prefix('.') {
            if let Some((field, value)) = default.trim_end_matches(';').split_once('=') {
                defaults.push((field.trim().to_owned(), value.trim().to_owned()));
            }
            continue;
        }
        if !rest.starts_with(|c: char| c.is_whitespace()) {
            continue;
        }
        let head = rest.split('{').next().unwrap_or_default().trim().to_owned();
        interprets.push(InterpretText {
            head,
            fields: body_statements(stmt)?,
        });
    }
    Ok((interprets, defaults))
}

/// Each key type of `xkb_types` in definition order, with the value of its
/// `modifiers=` statement (`"none"` when it has none).
pub(crate) fn type_modifier_texts(text: &str) -> Result<Vec<(String, String)>, XkbEditError> {
    let body = section(text, "xkb_types")?;
    let mut out = Vec::new();
    for r in statements(text, body, "xkb_types")? {
        let stmt = &text[r];
        let Some(rest) = stmt.strip_prefix("type") else {
            continue;
        };
        if !rest.starts_with(|c: char| c.is_whitespace()) {
            continue;
        }
        let Some((name, _)) = rest
            .trim_start()
            .strip_prefix('"')
            .and_then(|t| t.split_once('"'))
        else {
            continue;
        };
        let modifiers = body_statements(stmt)?
            .into_iter()
            .find_map(|f| {
                let (k, v) = f.split_once('=')?;
                k.trim()
                    .eq_ignore_ascii_case("modifiers")
                    .then(|| v.trim().to_owned())
            })
            .unwrap_or_else(|| "none".to_owned());
        out.push((name.to_owned(), modifiers));
    }
    Ok(out)
}

/// The explicit per-key properties of an `xkb_symbols` key entry, as text.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub(crate) struct KeyExplicitText {
    /// `(group, actions)` per `actions[group]= [ … ]` field (group 1-based),
    /// each action as written (`SetMods(modifiers=Shift)`).
    pub actions: Vec<(usize, Vec<String>)>,
    /// The `virtualMods=` / `vmods=` value, if the entry fixes the vmodmap.
    pub vmods: Option<String>,
    /// Whether the entry fixes the auto-repeat (`repeat=`).
    pub repeat: bool,
}

/// Every key entry of `xkb_symbols` that carries an explicit property
/// (actions, virtual modifiers or repeat), by key name.
pub(crate) fn key_explicit_texts(
    text: &str,
) -> Result<Vec<(String, KeyExplicitText)>, XkbEditError> {
    let body = section(text, "xkb_symbols")?;
    let mut out = Vec::new();
    for r in statements(text, body, "xkb_symbols")? {
        let stmt = &text[r];
        let Some(name) = key_stmt_name(stmt) else {
            continue;
        };
        let (kept, actions) = kept_key_fields(stmt, MAX_GROUPS)?;
        let mut explicit = KeyExplicitText::default();
        for field in actions {
            let rest = field["actions".len()..].trim_start();
            let (group, rest) = match rest.strip_prefix('[').and_then(|t| t.split_once(']')) {
                Some((g, rest)) => (group_index(g).unwrap_or(1), rest),
                None => (1, rest),
            };
            let list = rest
                .trim_start()
                .strip_prefix('=')
                .map(str::trim)
                .and_then(|l| l.strip_prefix('['))
                .and_then(|l| l.strip_suffix(']'))
                .ok_or(XkbEditError::Malformed("xkb_symbols"))?;
            explicit.actions.push((
                group,
                split_top_level(list, b',')
                    .into_iter()
                    .map(str::to_owned)
                    .collect(),
            ));
        }
        for field in kept {
            let Some((k, v)) = field.split_once('=') else {
                continue;
            };
            let k = k.trim();
            if k.eq_ignore_ascii_case("virtualMods") || k.eq_ignore_ascii_case("vmods") {
                explicit.vmods = Some(v.trim().to_owned());
            } else if k.eq_ignore_ascii_case("repeat") {
                explicit.repeat = true;
            }
        }
        if explicit != KeyExplicitText::default() {
            out.push((name.to_owned(), explicit));
        }
    }
    Ok(out)
}

/// The statements inside the braces of `stmt` (`interpret … { a; b; };`).
fn body_statements(stmt: &str) -> Result<Vec<String>, XkbEditError> {
    let Some(open) = stmt.find('{') else {
        return Ok(Vec::new());
    };
    let close =
        matching_close(stmt.as_bytes(), open).ok_or(XkbEditError::Malformed("statement"))?;
    Ok(split_top_level(&stmt[open + 1..close], b';')
        .into_iter()
        .map(str::to_owned)
        .collect())
}

// ─── writing ────────────────────────────────────────────────────────

/// A key entry in the serializer's layout; empty when there's nothing to say.
fn render_key(name: &str, kept: &[&str], groups: &[KeyGroupSpec], actions: &[&str]) -> String {
    let mut fields: Vec<String> = kept.iter().map(|f| (*f).to_owned()).collect();
    for (g, group) in groups.iter().enumerate() {
        if let Some(ty) = &group.type_name {
            fields.push(format!("type[{}]= \"{ty}\"", g + 1));
        }
    }
    for (g, group) in groups.iter().enumerate() {
        let syms: Vec<String> = if group.keysyms.is_empty() {
            vec!["NoSymbol".to_owned()]
        } else {
            group.keysyms.iter().map(|&s| keysym_text(s)).collect()
        };
        fields.push(format!("symbols[{}]= [ {} ]", g + 1, syms.join(", ")));
    }
    fields.extend(actions.iter().map(|a| (*a).to_owned()));
    if fields.is_empty() {
        return String::new();
    }
    format!("\tkey <{name}> {{\n\t\t{}\n\t}};\n", fields.join(",\n\t\t"))
}

/// A keysym as every libxkbcommon parses it. Hex is read as the keysym value
/// for anything from 10 up; the integers 0–9 would parse as the digit keysyms
/// `0`–`9`, and values above `XKB_KEYSYM_MAX` are rejected, so those (none of
/// which is an assigned keysym) are written as `NoSymbol`.
fn keysym_text(sym: u32) -> String {
    match sym {
        0 => "NoSymbol".to_owned(),
        1..=9 => {
            log::warn!("xkb edit: keysym {sym:#x} can't be written in keymap text; NoSymbol");
            "NoSymbol".to_owned()
        }
        s if s > KEYSYM_MAX => {
            log::warn!("xkb edit: keysym {s:#x} is out of range; NoSymbol");
            "NoSymbol".to_owned()
        }
        s => format!("{s:#x}"),
    }
}

/// The fields of an existing key entry that survive a rewrite: everything but
/// its types and symbols, with `actions[]` kept only for groups `< n_groups`.
/// Returns (other fields, action fields).
fn kept_key_fields(stmt: &str, n_groups: usize) -> Result<(Vec<&str>, Vec<&str>), XkbEditError> {
    let open = stmt
        .find('{')
        .ok_or(XkbEditError::Malformed("xkb_symbols"))?;
    let close =
        matching_close(stmt.as_bytes(), open).ok_or(XkbEditError::Malformed("xkb_symbols"))?;
    let mut kept = Vec::new();
    let mut actions = Vec::new();
    for field in split_top_level(&stmt[open + 1..close], b',') {
        let keyword = field
            .split(|c: char| c == '[' || c == '=' || c.is_whitespace())
            .next()
            .unwrap_or_default();
        if keyword.is_empty()
            || keyword.eq_ignore_ascii_case("symbols")
            || keyword.eq_ignore_ascii_case("type")
        {
            // `[ … ]` shorthand, `symbols[N]=`, `type=` / `type[N]=`.
            continue;
        }
        if keyword.eq_ignore_ascii_case("actions") {
            let group = field[keyword.len()..]
                .trim_start()
                .strip_prefix('[')
                .and_then(|t| t.split_once(']'))
                .map_or(Some(1), |(g, _)| group_index(g));
            if group.is_some_and(|g| g >= 1 && g <= n_groups) {
                actions.push(field);
            }
            continue;
        }
        kept.push(field);
    }
    Ok((kept, actions))
}

/// `1`, `Group1`, `group 1` → 1.
fn group_index(s: &str) -> Option<usize> {
    let s = s.trim();
    let digits = if s.len() >= 5 && s[..5].eq_ignore_ascii_case("group") {
        s[5..].trim()
    } else {
        s
    };
    digits.parse().ok()
}

/// Apply non-overlapping `(range, replacement)` edits to `text`.
fn apply_edits(text: &str, mut edits: Vec<(Range<usize>, String)>) -> String {
    edits.sort_by_key(|(r, _)| (r.start, r.end));
    let mut out = String::with_capacity(text.len() + 256);
    let mut pos = 0;
    for (r, rep) in edits {
        out.push_str(&text[pos..r.start]);
        out.push_str(&rep);
        pos = r.end;
    }
    out.push_str(&text[pos..]);
    out
}

// ─── reading ────────────────────────────────────────────────────────

/// The byte range between the braces of the section `keyword` opens.
fn section(text: &str, keyword: &'static str) -> Result<Range<usize>, XkbEditError> {
    let start = text
        .match_indices(keyword)
        .map(|(i, _)| i)
        .find(|&i| {
            (i == 0 || text.as_bytes()[i - 1] == b'\n')
                && text[i + keyword.len()..]
                    .chars()
                    .next()
                    .is_some_and(|c| c.is_whitespace() || c == '"' || c == '{')
        })
        .ok_or(XkbEditError::MissingSection(keyword))?;
    let open = start
        + text[start..]
            .find('{')
            .ok_or(XkbEditError::Malformed(keyword))?;
    let close = matching_close(text.as_bytes(), open).ok_or(XkbEditError::Malformed(keyword))?;
    Ok(open + 1..close)
}

/// The top-level statements of a section body, each from its first non-blank
/// byte to just past its `;`.
fn statements(
    text: &str,
    body: Range<usize>,
    section: &'static str,
) -> Result<Vec<Range<usize>>, XkbEditError> {
    let bytes = text.as_bytes();
    let mut out = Vec::new();
    let mut i = body.start;
    loop {
        while i < body.end && bytes[i].is_ascii_whitespace() {
            i += 1;
        }
        if i >= body.end {
            return Ok(out);
        }
        let start = i;
        let mut depth = 0usize;
        loop {
            if i >= body.end {
                return Err(XkbEditError::Malformed(section));
            }
            match bytes[i] {
                b'"' => {
                    i = skip_string(bytes, i).ok_or(XkbEditError::Malformed(section))?;
                    continue;
                }
                b'{' | b'[' | b'(' => depth += 1,
                b'}' | b']' | b')' => {
                    depth = depth
                        .checked_sub(1)
                        .ok_or(XkbEditError::Malformed(section))?;
                }
                b';' if depth == 0 => break,
                _ => {}
            }
            i += 1;
        }
        i += 1;
        out.push(start..i);
    }
}

/// Index of the `}` closing the `{` at `open`.
fn matching_close(bytes: &[u8], open: usize) -> Option<usize> {
    let mut depth = 0usize;
    let mut i = open;
    while i < bytes.len() {
        match bytes[i] {
            b'"' => {
                i = skip_string(bytes, i)?;
                continue;
            }
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
        i += 1;
    }
    None
}

/// Index just past the string literal that opens at `open`.
fn skip_string(bytes: &[u8], open: usize) -> Option<usize> {
    let mut i = open + 1;
    while i < bytes.len() {
        match bytes[i] {
            b'\\' => i += 2,
            b'"' => return Some(i + 1),
            _ => i += 1,
        }
    }
    None
}

/// Split at top-level `sep`, trimmed, empty pieces dropped.
fn split_top_level(s: &str, sep: u8) -> Vec<&str> {
    let bytes = s.as_bytes();
    let mut out = Vec::new();
    let mut depth = 0usize;
    let mut start = 0;
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'"' => {
                i = skip_string(bytes, i).unwrap_or(bytes.len());
                continue;
            }
            b'{' | b'[' | b'(' => depth += 1,
            b'}' | b']' | b')' => depth = depth.saturating_sub(1),
            c if c == sep && depth == 0 => {
                out.push(s[start..i].trim());
                start = i + 1;
            }
            _ => {}
        }
        i += 1;
    }
    out.push(s[start..].trim());
    out.retain(|p| !p.is_empty());
    out
}

/// The whole lines a statement occupies: back to the start of its line and
/// forward over its line break, so removing it leaves no blank line.
fn line_extent(text: &str, r: Range<usize>) -> Range<usize> {
    let bytes = text.as_bytes();
    let mut start = r.start;
    while start > 0 && matches!(bytes[start - 1], b' ' | b'\t') {
        start -= 1;
    }
    let mut end = r.end;
    while end < bytes.len() && matches!(bytes[end], b' ' | b'\t') {
        end += 1;
    }
    if end < bytes.len() && bytes[end] == b'\n' {
        end += 1;
    }
    start..end
}

/// `<NAME> = 38;` → `("NAME", 38)`.
fn keycode_def(stmt: &str) -> Option<(&str, u32)> {
    let (name, rest) = stmt.strip_prefix('<')?.split_once('>')?;
    let value = rest
        .trim()
        .strip_prefix('=')?
        .trim()
        .strip_suffix(';')?
        .trim();
    Some((name, value.parse().ok()?))
}

/// `alias <A> = <B>;` → `("A", "B")`.
fn alias_pair(stmt: &str) -> Option<(&str, &str)> {
    let rest = stmt.strip_prefix("alias")?.trim_start();
    let (alias, rest) = rest.strip_prefix('<')?.split_once('>')?;
    let target = rest
        .trim()
        .strip_prefix('=')?
        .trim()
        .strip_prefix('<')?
        .split_once('>')?
        .0;
    Some((alias, target))
}

fn alias_def(stmt: &str) -> Option<&str> {
    alias_pair(stmt).map(|(a, _)| a)
}

/// `keyword = 8;` → 8.
fn assignment(stmt: &str, keyword: &str) -> Option<u32> {
    let rest = stmt.strip_prefix(keyword)?.trim_start().strip_prefix('=')?;
    rest.trim().strip_suffix(';')?.trim().parse().ok()
}

/// `key <NAME> { … };` → `NAME`.
fn key_stmt_name(stmt: &str) -> Option<&str> {
    let rest = stmt.strip_prefix("key")?;
    if !rest.starts_with(|c: char| c.is_whitespace()) {
        return None;
    }
    rest.trim_start()
        .strip_prefix('<')?
        .split_once('>')
        .map(|(n, _)| n)
}

fn is_modifier_map(stmt: &str) -> bool {
    stmt.strip_prefix("modifier_map")
        .is_some_and(|r| r.starts_with(|c: char| c.is_whitespace()))
}

/// The keycode name `name` stands for: itself, or an alias's target.
fn canonical_key_name(text: &str, name: &str) -> Result<String, XkbEditError> {
    let body = section(text, "xkb_keycodes")?;
    let mut alias_target = None;
    for r in statements(text, body, "xkb_keycodes")? {
        let stmt = &text[r];
        if keycode_def(stmt).is_some_and(|(n, _)| n == name) {
            return Ok(name.to_owned());
        }
        if let Some((a, t)) = alias_pair(stmt)
            && a == name
        {
            alias_target = Some(t.to_owned());
        }
    }
    alias_target.ok_or_else(|| XkbEditError::UnknownKey(name.to_owned()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::kms::xkb::{explicit_type_names, golden_keymap, keymap_modmap};
    use xkbcommon::xkb::{self, Keycode, Keymap};

    /// The four frozen fixtures, as `golden_keymap` keys them.
    const FIXTURES: [(&str, Option<&str>); 4] = [
        ("us", None),
        ("gb", None),
        ("de", None),
        ("us,ru", Some("grp:alt_shift_toggle")),
    ];

    /// What an edit operates on in production: xkbcommon's own V1 dump of
    /// the live keymap.
    fn dump(km: &Keymap) -> String {
        keymap_text(km)
    }

    fn compile(text: &str) -> Keymap {
        let ctx = xkb::Context::new(xkb::CONTEXT_NO_FLAGS);
        Keymap::new_from_string(
            &ctx,
            text.to_owned(),
            xkb::KEYMAP_FORMAT_TEXT_V1,
            xkb::KEYMAP_COMPILE_NO_FLAGS,
        )
        .expect("edited keymap text must compile")
    }

    /// A key as clients see it, read back through xkbcommon: per group, per
    /// level, the keysyms and the modifier masks that select the level.
    #[derive(Debug, PartialEq, Eq)]
    struct KeySig {
        groups: Vec<Vec<(Vec<u32>, Vec<u32>)>>,
    }

    fn key_sig(km: &Keymap, kc: u32) -> KeySig {
        let key = Keycode::new(kc);
        let groups = (0..km.num_layouts_for_key(key))
            .map(|g| {
                (0..km.num_levels_for_key(key, g))
                    .map(|l| {
                        let syms = km
                            .key_get_syms_by_level(key, g, l)
                            .iter()
                            .map(|s| s.raw())
                            .collect();
                        let mut masks = [0u32; 64];
                        let n = km.key_get_mods_for_level(key, g, l, &mut masks);
                        let mut masks = masks[..n].to_vec();
                        masks.sort_unstable();
                        (syms, masks)
                    })
                    .collect()
            })
            .collect();
        KeySig { groups }
    }

    /// Every key but `except` reads back identically, repeat flag included.
    fn assert_untouched(before: &Keymap, after: &Keymap, except: &[u32]) {
        // xkbcommon's range follows the keycodes that exist, so naming
        // keycode 8 moves its minimum from 9 to 8: compare over both ranges.
        let lo = before.min_keycode().raw().min(after.min_keycode().raw());
        let hi = before.max_keycode().raw().max(after.max_keycode().raw());
        for kc in lo..=hi {
            if except.contains(&kc) {
                continue;
            }
            assert_eq!(
                key_sig(after, kc),
                key_sig(before, kc),
                "untouched keycode {kc} changed"
            );
            assert_eq!(
                after.key_repeats(Keycode::new(kc)),
                before.key_repeats(Keycode::new(kc)),
                "repeat flag of untouched keycode {kc} changed"
            );
        }
    }

    /// The spec that reproduces keycode `kc` of `km`: its keysyms per level
    /// and its explicit type names, both read from xkbcommon.
    fn spec_of(km: &Keymap, kc: u8) -> Vec<KeyGroupSpec> {
        let key = Keycode::new(u32::from(kc));
        let types = explicit_type_names(km).remove(&kc).unwrap_or_default();
        (0..km.num_layouts_for_key(key))
            .map(|g| KeyGroupSpec {
                type_name: types[g as usize].clone(),
                keysyms: (0..km.num_levels_for_key(key, g))
                    .map(|l| {
                        let syms = km.key_get_syms_by_level(key, g, l);
                        assert!(syms.len() <= 1, "source key {kc} has a multi-keysym level");
                        syms.first().map_or(0, |s| s.raw())
                    })
                    .collect(),
            })
            .collect()
    }

    #[test]
    fn ensure_keycode_name_keeps_an_existing_name() {
        let km = golden_keymap("us", None);
        let text = dump(&km);
        let (out, name) = ensure_keycode_name(&text, 38).expect("named keycode");
        assert_eq!(Some(name.as_str()), km.key_get_name(Keycode::new(38)));
        assert_eq!(out, text, "a named keycode leaves the text as it was");
    }

    #[test]
    fn ensure_keycode_name_names_an_unnamed_keycode() {
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            assert_eq!(km.key_get_name(Keycode::new(8)), None, "precondition");
            let (out, name) = ensure_keycode_name(&dump(&km), 8).expect("names keycode 8");
            let after = compile(&out);
            assert_eq!(after.key_get_name(Keycode::new(8)), Some(name.as_str()));
            assert_eq!(after.key_by_name(&name).map(|k| k.raw()), Some(8));
            assert!(name.len() <= 4, "X key names are 4 bytes on the wire");
            for kc in 9..=before_max(&km) {
                assert_eq!(
                    after.key_get_name(Keycode::new(kc)),
                    km.key_get_name(Keycode::new(kc)),
                    "{layout}: name of keycode {kc}"
                );
            }
            assert_untouched(&km, &after, &[]);
        }
    }

    fn before_max(km: &Keymap) -> u32 {
        km.max_keycode().raw()
    }

    #[test]
    fn set_key_replaces_a_key_with_another_keys_definition() {
        // Source keys cover: explicit multi-level type (FK01 CTRL+ALT, 5
        // levels), KEYPAD (KPDL, two groups on us,ru), a non-default modifier
        // type (LFSH PC_ALT_LEVEL2), a plain alphabetic key (AD01) and a
        // four-level key (AE10 on de, AE08 group 2 on us,ru).
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            let text = dump(&km);
            for source in [67u8, 91, 50, 24, 19, 17] {
                let spec = spec_of(&km, source);
                let out = set_key(&text, "AC01", &spec).expect("set_key");
                let after = compile(&out);
                assert_eq!(
                    key_sig(&after, 38),
                    key_sig(&km, u32::from(source)),
                    "{layout}: <AC01> must now read back as keycode {source}"
                );
                assert_untouched(&km, &after, &[38]);
                assert_eq!(keymap_modmap(&after), keymap_modmap(&km), "modmap");
            }
        }
    }

    #[test]
    fn set_key_accepts_an_alias() {
        // <AC12> is an alias of <BKSL> in every fixture.
        let km = golden_keymap("us", None);
        let bksl = km.key_by_name("BKSL").expect("BKSL").raw();
        let spec = spec_of(&km, 38);
        let after = compile(&set_key(&dump(&km), "AC12", &spec).expect("alias"));
        assert_eq!(key_sig(&after, bksl), key_sig(&km, 38));
        assert_untouched(&km, &after, &[bksl]);
    }

    #[test]
    fn set_key_inserts_a_key_that_has_no_symbols() {
        let km = golden_keymap("us", None);
        assert_eq!(km.num_layouts_for_key(Keycode::new(248)), 0, "precondition");
        let spec = spec_of(&km, 240);
        let after = compile(&set_key(&dump(&km), "I248", &spec).expect("insert"));
        assert_eq!(key_sig(&after, 248), key_sig(&km, 240));
        assert_untouched(&km, &after, &[248]);
    }

    #[test]
    fn set_key_on_an_unnamed_keycode() {
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            let (named, name) = ensure_keycode_name(&dump(&km), 8).expect("name");
            let spec = spec_of(&km, 38);
            let after = compile(&set_key(&named, &name, &spec).expect("set"));
            assert_eq!(key_sig(&after, 8), key_sig(&km, 38), "{layout}");
            assert_untouched(&km, &after, &[8]);
        }
    }

    #[test]
    fn set_key_without_groups_clears_the_key() {
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            let after = compile(&set_key(&dump(&km), "AC01", &[]).expect("clear"));
            assert_eq!(after.num_layouts_for_key(Keycode::new(38)), 0, "{layout}");
            assert_untouched(&km, &after, &[38]);
        }
    }

    #[test]
    fn set_key_keeps_explicit_repeat_vmods_and_actions() {
        // Give <CAPS> explicit properties the fixtures don't carry, and take
        // xkbcommon's own dump of that as the input, so the input is in the
        // serializer's format.
        let km = golden_keymap("us", None);
        let text = dump(&km);
        let caps = "\tkey <CAPS> {\t[ 0xffe5 ] };\n";
        assert!(text.contains(caps), "fixture shape");
        let crafted = text.replace(
            caps,
            "\tkey <CAPS> {\n\t\trepeat= No,\n\t\tvmods= NumLock,\n\t\t\
             symbols[1]= [ 0xffe5 ],\n\t\tactions[1]= [ LockMods(modifiers=Mod3) ]\n\t};\n",
        );
        let before = compile(&dump(&compile(&crafted)));
        let input = dump(&before);
        assert!(input.contains("repeat= No") || input.contains("repeat=No"));
        assert!(input.contains("actions[1]"), "explicit action is dumped");

        // Rebind the key to Control_L: the interpret for Control_L would give
        // SetMods(Control), but the explicit LockMods(Mod3) must survive.
        let spec = [KeyGroupSpec {
            type_name: None,
            keysyms: vec![0xffe3],
        }];
        let after = compile(&set_key(&input, "CAPS", &spec).expect("set"));
        let caps_kc = Keycode::new(66);
        assert_eq!(after.key_get_syms_by_level(caps_kc, 0, 0)[0].raw(), 0xffe3);
        assert_eq!(after.key_repeats(caps_kc), before.key_repeats(caps_kc));
        assert!(!after.key_repeats(caps_kc));
        let locked = |k: &Keymap| {
            let mut st = xkb::State::new(k);
            st.update_key(caps_kc, xkb::KeyDirection::Down);
            st.update_key(caps_kc, xkb::KeyDirection::Up);
            st.serialize_mods(xkb::STATE_MODS_LOCKED)
        };
        assert_ne!(locked(&before), 0, "precondition: the action locks");
        assert_eq!(locked(&after), locked(&before), "explicit action kept");
        assert_untouched(&before, &after, &[66]);
    }

    #[test]
    fn set_key_rejects_what_it_cannot_express() {
        let text = dump(&golden_keymap("us", None));
        let one = KeyGroupSpec {
            type_name: None,
            keysyms: vec![0x61],
        };
        assert!(set_key(&text, "NOPE", std::slice::from_ref(&one)).is_err());
        assert!(set_key(&text, "AC01", &vec![one.clone(); 5]).is_err());
        let bad_type = KeyGroupSpec {
            type_name: Some("A\"B".into()),
            keysyms: vec![0x61],
        };
        assert!(set_key(&text, "AC01", &[bad_type]).is_err());
    }

    #[test]
    fn set_modifier_map_round_trips() {
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            // Headline xmodmap case: Caps from Lock to Control.
            let mut modmap = keymap_modmap(&km);
            assert_eq!(modmap[66], 0x02, "{layout}: precondition CAPS in Lock");
            modmap[66] = 0x04;
            let after = compile(&set_modifier_map(&dump(&km), &modmap).expect("modmap"));
            assert_eq!(keymap_modmap(&after), modmap, "{layout}");
            for kc in 8..=255 {
                assert_eq!(key_sig(&after, kc), key_sig(&km, kc), "{layout}: {kc}");
            }
        }
    }

    #[test]
    fn set_modifier_map_can_clear_everything() {
        let km = golden_keymap("de", None);
        let out = set_modifier_map(&dump(&km), &[0u8; 256]).expect("modmap");
        assert!(!out.contains("modifier_map"));
        assert_eq!(keymap_modmap(&compile(&out)), [0u8; 256]);
    }

    /// xkbcommon (like xkbcomp) keeps one modifier per key in its modmap: a
    /// key listed under two `modifier_map`s ends up in the last one only.
    /// The core modmap allows several, so such a map can't go through the
    /// text and must be refused, not silently collapsed.
    #[test]
    fn set_modifier_map_refuses_a_key_in_two_modifiers() {
        let km = golden_keymap("us", None);
        let mut modmap = keymap_modmap(&km);
        modmap[50] |= 0x20; // LFSH: Shift and Mod3
        let collapsed = {
            let mut text = dump(&km);
            text = text.replace(
                "\tmodifier_map Mod3 { <LVL5> };",
                "\tmodifier_map Mod3 { <LVL5>, <LFSH> };",
            );
            keymap_modmap(&compile(&text))[50]
        };
        assert_eq!(
            collapsed.count_ones(),
            1,
            "xkbcommon collapses to one modifier"
        );
        assert_eq!(
            set_modifier_map(&dump(&km), &modmap),
            Err(XkbEditError::MultipleModifiers(50))
        );
    }

    #[test]
    fn set_modifier_map_names_an_unnamed_keycode() {
        let km = golden_keymap("us", None);
        let (named, name) = ensure_keycode_name(&dump(&km), 8).expect("name");
        let spec = spec_of(&km, 133); // LWIN
        let with_key = set_key(&named, &name, &spec).expect("set");
        let mut modmap = keymap_modmap(&km);
        modmap[8] = 0x20; // Mod3
        let text = set_modifier_map(&with_key, &modmap).expect("modmap");
        assert_eq!(keymap_modmap(&compile(&text)), modmap);

        // Without a prior name, set_modifier_map names the keycode itself.
        let mut modmap2 = keymap_modmap(&km);
        modmap2[8] = 0x20;
        let out2 = set_modifier_map(&dump(&km), &modmap2).expect("modmap");
        let after2 = compile(&out2);
        assert!(after2.key_get_name(Keycode::new(8)).is_some());
        assert_eq!(keymap_modmap(&after2), modmap2);
    }

    /// Each probe key compiles with its type: the level count xkbcommon gives
    /// the probe is the one the `xkb_types` section declares for that name.
    #[test]
    fn type_probes_carry_each_type() {
        for (layout, options) in FIXTURES {
            let km = golden_keymap(layout, options);
            let text = dump(&km);
            let names = type_names(&text).expect("types");
            assert!(names.iter().any(|n| n == "ONE_LEVEL"));
            assert!(names.iter().any(|n| n == "FOUR_LEVEL"));
            let (probed, kcs) = add_type_probes(&text, &names).expect("probes");
            let after = compile(&probed);
            assert_eq!(kcs.len(), names.len());
            for (name, kc) in names.iter().zip(&kcs) {
                let levels = after.num_levels_for_key(Keycode::new(*kc), 0);
                let expected = match name.as_str() {
                    "ONE_LEVEL" => 1,
                    "TWO_LEVEL" | "ALPHABETIC" | "KEYPAD" => 2,
                    "FOUR_LEVEL" | "FOUR_LEVEL_ALPHABETIC" | "FOUR_LEVEL_SEMIALPHABETIC" => 4,
                    _ => levels,
                };
                assert_eq!(levels, expected, "{layout}: probe for {name}");
            }
            assert_untouched(&km, &after, &kcs);
        }
    }
}
